### ISSUE TITLE
A Pull Request?

### ISSUE THREAD

**Issue by erdemuncuoglu** [OrdinaryJellyfish/reactphp-static#1]
Hello Tristian,

I made some changes and a compatibility fix to run with the recent version of reactPHP HTTP on my [fork](/erdemuncuoglu/reactphp-static)  
If you mind to maintain your repository I'd like to open a pull request. Or else unwillingly I will publish my fork.

**Comment by OrdinaryJellyfish** [comment]
I have no current plans to maintain this package. You're more than welcome to publish your fork :)

Thank you for the contributions though, I like what you've done!

**Comment by OrdinaryJellyfish** [comment]
By the way, taking a second look at your code, I'd suggest updating the namespace to your username rather than mine to prevent conflicts. And since this is *your* fork, maybe add yourself to the author array of the composer.json since you wrote some of the code too!!

**Comment by erdemuncuoglu** [comment]
I intentionally kept the namespace hoping youı will update your package. This is how it should be at first hand.
Anyway I'm gonna apply your suggestions then publish my work.

Thanks for your efforts.
